// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef _UI_COMP_PANELOFTITLE_H
#define _UI_COMP_PANELOFTITLE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PanelOfTitle
#define UI_COMP_PANELOFTITLE_PANELOFTITLE 0
#define UI_COMP_PANELOFTITLE_LABLE4G 1
#define UI_COMP_PANELOFTITLE_BAR14G 2
#define UI_COMP_PANELOFTITLE_BAR24G 3
#define UI_COMP_PANELOFTITLE_BAR34G 4
#define UI_COMP_PANELOFTITLE_PANELOFBATTERY 5
#define UI_COMP_PANELOFTITLE_PANELOFBATTERY_BARBATTERY 6
#define UI_COMP_PANELOFTITLE_LABELVOICELEVEL1 7
#define UI_COMP_PANELOFTITLE_LABELVOICELEVEL2 8
#define UI_COMP_PANELOFTITLE_LABELVOICENOUN 9
#define UI_COMP_PANELOFTITLE_LABELMICOFF 10
#define UI_COMP_PANELOFTITLE_LABELMICON 11
#define _UI_COMP_PANELOFTITLE_NUM 12
lv_obj_t * ui_PanelOfTitle_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
