// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32

#include "ui.h"

// COMPONENT PanelOfTitle

lv_obj_t * ui_PanelOfTitle_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_PanelOfTitle;
    cui_PanelOfTitle = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_PanelOfTitle, 235);
    lv_obj_set_height(cui_PanelOfTitle, 34);
    lv_obj_set_x(cui_PanelOfTitle, 0);
    lv_obj_set_y(cui_PanelOfTitle, -124);
    lv_obj_set_align(cui_PanelOfTitle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PanelOfTitle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(cui_PanelOfTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_PanelOfTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lable4g;
    cui_lable4g = lv_label_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_lable4g, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lable4g, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_lable4g, -96);
    lv_obj_set_y(cui_lable4g, 0);
    lv_obj_set_align(cui_lable4g, LV_ALIGN_CENTER);
    lv_label_set_text(cui_lable4g, "4G");

    lv_obj_t * cui_Bar14g;
    cui_Bar14g = lv_obj_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_Bar14g, 13);
    lv_obj_set_height(cui_Bar14g, 20);
    lv_obj_set_x(cui_Bar14g, -74);
    lv_obj_set_y(cui_Bar14g, 1);
    lv_obj_set_align(cui_Bar14g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Bar14g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Bar14g, lv_color_hex(0x68D790), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Bar14g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Bar24g;
    cui_Bar24g = lv_obj_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_Bar24g, 13);
    lv_obj_set_height(cui_Bar24g, 20);
    lv_obj_set_x(cui_Bar24g, -60);
    lv_obj_set_y(cui_Bar24g, 1);
    lv_obj_set_align(cui_Bar24g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Bar24g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Bar24g, lv_color_hex(0x68D790), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Bar24g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Bar34g;
    cui_Bar34g = lv_obj_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_Bar34g, 13);
    lv_obj_set_height(cui_Bar34g, 20);
    lv_obj_set_x(cui_Bar34g, -45);
    lv_obj_set_y(cui_Bar34g, 1);
    lv_obj_set_align(cui_Bar34g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Bar34g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Bar34g, lv_color_hex(0x68D790), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Bar34g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_PanelOfBattery;
    cui_PanelOfBattery = lv_obj_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_PanelOfBattery, 41);
    lv_obj_set_height(cui_PanelOfBattery, 23);
    lv_obj_set_x(cui_PanelOfBattery, 81);
    lv_obj_set_y(cui_PanelOfBattery, 0);
    lv_obj_set_align(cui_PanelOfBattery, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PanelOfBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_BarBattery;
    cui_BarBattery = lv_bar_create(cui_PanelOfBattery);
    lv_bar_set_value(cui_BarBattery, 70, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_BarBattery, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_BarBattery, 34);
    lv_obj_set_height(cui_BarBattery, 15);
    lv_obj_set_x(cui_BarBattery, 1);
    lv_obj_set_y(cui_BarBattery, -1);
    lv_obj_set_align(cui_BarBattery, LV_ALIGN_CENTER);

    lv_obj_t * cui_Labelvoicelevel1;
    cui_Labelvoicelevel1 = lv_label_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_Labelvoicelevel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Labelvoicelevel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Labelvoicelevel1, 25);
    lv_obj_set_y(cui_Labelvoicelevel1, 0);
    lv_obj_set_align(cui_Labelvoicelevel1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Labelvoicelevel1, "");
    lv_obj_add_flag(cui_Labelvoicelevel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(cui_Labelvoicelevel1, &ui_font_IconFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Labelvoicelevel2;
    cui_Labelvoicelevel2 = lv_label_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_Labelvoicelevel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Labelvoicelevel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Labelvoicelevel2, 25);
    lv_obj_set_y(cui_Labelvoicelevel2, 0);
    lv_obj_set_align(cui_Labelvoicelevel2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Labelvoicelevel2, "");
    lv_obj_add_flag(cui_Labelvoicelevel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(cui_Labelvoicelevel2, &ui_font_IconFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Labelvoicenoun;
    cui_Labelvoicenoun = lv_label_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_Labelvoicenoun, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Labelvoicenoun, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Labelvoicenoun, 25);
    lv_obj_set_y(cui_Labelvoicenoun, 0);
    lv_obj_set_align(cui_Labelvoicenoun, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Labelvoicenoun, "");
    lv_obj_set_style_text_font(cui_Labelvoicenoun, &ui_font_IconFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Labelmicoff;
    cui_Labelmicoff = lv_label_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_Labelmicoff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Labelmicoff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Labelmicoff, 48);
    lv_obj_set_y(cui_Labelmicoff, 0);
    lv_obj_set_align(cui_Labelmicoff, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Labelmicoff, "");
    lv_obj_set_style_text_font(cui_Labelmicoff, &ui_font_IconFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Labelmicon;
    cui_Labelmicon = lv_label_create(cui_PanelOfTitle);
    lv_obj_set_width(cui_Labelmicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Labelmicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Labelmicon, 48);
    lv_obj_set_y(cui_Labelmicon, 0);
    lv_obj_set_align(cui_Labelmicon, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Labelmicon, "");
    lv_obj_add_flag(cui_Labelmicon, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(cui_Labelmicon, &ui_font_IconFont1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANELOFTITLE_NUM);
    children[UI_COMP_PANELOFTITLE_PANELOFTITLE] = cui_PanelOfTitle;
    children[UI_COMP_PANELOFTITLE_LABLE4G] = cui_lable4g;
    children[UI_COMP_PANELOFTITLE_BAR14G] = cui_Bar14g;
    children[UI_COMP_PANELOFTITLE_BAR24G] = cui_Bar24g;
    children[UI_COMP_PANELOFTITLE_BAR34G] = cui_Bar34g;
    children[UI_COMP_PANELOFTITLE_PANELOFBATTERY] = cui_PanelOfBattery;
    children[UI_COMP_PANELOFTITLE_PANELOFBATTERY_BARBATTERY] = cui_BarBattery;
    children[UI_COMP_PANELOFTITLE_LABELVOICELEVEL1] = cui_Labelvoicelevel1;
    children[UI_COMP_PANELOFTITLE_LABELVOICELEVEL2] = cui_Labelvoicelevel2;
    children[UI_COMP_PANELOFTITLE_LABELVOICENOUN] = cui_Labelvoicenoun;
    children[UI_COMP_PANELOFTITLE_LABELMICOFF] = cui_Labelmicoff;
    children[UI_COMP_PANELOFTITLE_LABELMICON] = cui_Labelmicon;
    lv_obj_add_event_cb(cui_PanelOfTitle, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_PanelOfTitle, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_PanelOfTitle_create_hook(cui_PanelOfTitle);
    return cui_PanelOfTitle;
}

