// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32

#include "ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_PanelTopTitle = NULL;
lv_obj_t * ui_LabelTxt4G = NULL;
lv_obj_t * ui_Bar4gsignal = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_PanelMainShow = NULL;
lv_obj_t * ui_ButtonAI = NULL;
lv_obj_t * ui_ImageAI = NULL;
lv_obj_t * ui_ButtonLink = NULL;
lv_obj_t * ui_ImageLink = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelTopTitle = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelTopTitle, 128);
    lv_obj_set_height(ui_PanelTopTitle, 20);
    lv_obj_set_x(ui_PanelTopTitle, 0);
    lv_obj_set_y(ui_PanelTopTitle, 1);
    lv_obj_set_align(ui_PanelTopTitle, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelTopTitle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTxt4G = lv_label_create(ui_PanelTopTitle);
    lv_obj_set_width(ui_LabelTxt4G, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTxt4G, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTxt4G, -50);
    lv_obj_set_y(ui_LabelTxt4G, 0);
    lv_obj_set_align(ui_LabelTxt4G, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTxt4G, "4G");

    ui_Bar4gsignal = lv_bar_create(ui_PanelTopTitle);
    lv_bar_set_value(ui_Bar4gsignal, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4gsignal, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4gsignal, 20);
    lv_obj_set_height(ui_Bar4gsignal, 10);
    lv_obj_set_x(ui_Bar4gsignal, -26);
    lv_obj_set_y(ui_Bar4gsignal, 0);
    lv_obj_set_align(ui_Bar4gsignal, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar4gsignal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar4gsignal, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_PanelTopTitle);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, 24);
    lv_obj_set_y(ui_LabelTime, 0);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "10.30");

    ui_PanelMainShow = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelMainShow, 128);
    lv_obj_set_height(ui_PanelMainShow, 108);
    lv_obj_set_x(ui_PanelMainShow, 0);
    lv_obj_set_y(ui_PanelMainShow, 1);
    lv_obj_set_align(ui_PanelMainShow, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PanelMainShow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelMainShow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAI = lv_btn_create(ui_PanelMainShow);
    lv_obj_set_width(ui_ButtonAI, 50);
    lv_obj_set_height(ui_ButtonAI, 50);
    lv_obj_set_x(ui_ButtonAI, -9);
    lv_obj_set_y(ui_ButtonAI, -9);
    lv_obj_set_align(ui_ButtonAI, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ButtonAI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAI, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonAI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonAI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonAI, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonAI, lv_color_hex(0xFF9900), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ButtonAI, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ImageAI = lv_img_create(ui_ButtonAI);
    lv_img_set_src(ui_ImageAI, &ui_img_648949130);
    lv_obj_set_width(ui_ImageAI, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_ImageAI, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_align(ui_ImageAI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAI, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonLink = lv_btn_create(ui_PanelMainShow);
    lv_obj_set_width(ui_ButtonLink, 50);
    lv_obj_set_height(ui_ButtonLink, 50);
    lv_obj_set_x(ui_ButtonLink, 32);
    lv_obj_set_y(ui_ButtonLink, -9);
    lv_obj_set_align(ui_ButtonLink, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLink, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLink, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLink, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLink, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonLink, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonLink, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonLink, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonLink, lv_color_hex(0xFF9900), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ButtonLink, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ImageLink = lv_img_create(ui_ButtonLink);
    lv_img_set_src(ui_ImageLink, &ui_img_160084951);
    lv_obj_set_width(ui_ImageLink, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_ImageLink, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_ImageLink, 1);
    lv_obj_set_y(ui_ImageLink, 0);
    lv_obj_set_align(ui_ImageLink, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLink, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLink, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_PanelTopTitle = NULL;
    ui_LabelTxt4G = NULL;
    ui_Bar4gsignal = NULL;
    ui_LabelTime = NULL;
    ui_PanelMainShow = NULL;
    ui_ButtonAI = NULL;
    ui_ImageAI = NULL;
    ui_ButtonLink = NULL;
    ui_ImageLink = NULL;

}
