// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_PanelTopTitle;
extern lv_obj_t * ui_LabelTxt4G;
extern lv_obj_t * ui_Bar4gsignal;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_PanelMainShow;
extern lv_obj_t * ui_ButtonAI;
extern lv_obj_t * ui_ImageAI;
extern lv_obj_t * ui_ButtonLink;
extern lv_obj_t * ui_ImageLink;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

