// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32

#ifndef UI_QRSCREEN_H
#define UI_QRSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_QRScreen
extern void ui_QRScreen_screen_init(void);
extern void ui_QRScreen_screen_destroy(void);
extern lv_obj_t * ui_QRScreen;
extern lv_obj_t * ui_PanelQR;
extern lv_obj_t * ui_ImageQR;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

