// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ESP32

#include "ui.h"

lv_obj_t * ui_QRScreen = NULL;
lv_obj_t * ui_PanelQR = NULL;
lv_obj_t * ui_ImageQR = NULL;
// event funtions

// build funtions

void ui_QRScreen_screen_init(void)
{
    ui_QRScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_QRScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelQR = lv_obj_create(ui_QRScreen);
    lv_obj_set_width(ui_PanelQR, 120);
    lv_obj_set_height(ui_PanelQR, 120);
    lv_obj_set_x(ui_PanelQR, 0);
    lv_obj_set_y(ui_PanelQR, -1);
    lv_obj_set_align(ui_PanelQR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelQR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageQR = lv_img_create(ui_PanelQR);
    lv_obj_set_width(ui_ImageQR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageQR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageQR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageQR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageQR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_QRScreen_screen_destroy(void)
{
    if(ui_QRScreen) lv_obj_del(ui_QRScreen);

    // NULL screen variables
    ui_QRScreen = NULL;
    ui_PanelQR = NULL;
    ui_ImageQR = NULL;

}
